services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: mfnp
      POSTGRES_USER: mfnp
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - dados_postgres:/var/lib/postgresql/data

volumes:
  dados_postgres:
